name: 'Build and publish release'

on:
  release:
    types: [published]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v4
      name: Install dependencies
      with:
        python-version: 3.9
        cache: poetry
    - run: poetry install

    - name: Build and publish wheels
      run: poetry publish --build -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }}
